FROM --platform=$BUILDPLATFORM debian:buster-slim

ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM"

RUN apt update && apt install -y python3-dev python3-venv build-essential

COPY . /opt/raspberry-client

RUN /usr/bin/python3 -m venv /opt/raspberry-client/nfc_env

RUN /opt/raspberry-client/nfc_env/bin/pip install wheel
RUN /opt/raspberry-client/nfc_env/bin/pip install -r /opt/raspberry-client/requirements.txt

RUN uname -a
