name: CI

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=local,dest=${PWD}/builder" \
          --file Dockerfile .

    - name: Copy and create tarball
      run: |
        pwd
        mv builder/opt/raspberry-client .
        ln -sf /usr/bin/python3 raspberry-client/nfc_env/bin/python
        tar czf raspberry-client.tar.gz raspberry-client
        docker ps -a

    - name: Archive tarball
      uses: actions/upload-artifact@v1
      with:
        name: raspberry-client
        path: raspberry-client.tar.gz
