name: CI

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=local,dest=${PWD}/builder" \
          --file Dockerfile .

    - name: Run a multi-line script
      run: |
        ls
        pwd
        env
        docker ps
        ls /opt
        docker images -a
        ls builder
        ls builder/opt/*
