name: CI

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=local,dest=${PWD}/builder" \
          --file Dockerfile .

    - name: Copy and create tarball
      run: |
        pwd
        mkdir opt
        mv builder/opt/raspberry-client opt
        ln -sf /usr/bin/python3 opt/raspberry-client/nfc_env/bin/python
        #tar czf raspberry-client.tar.gz raspberry-client

    - uses: singingwolfboy/build-dpkg-buster@v1
      id: build
      with:
        args: -us -uc

    - name: Test
      run: |
        echo ${{ steps.build.outputs.filename }}

    - name: Archive package
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.build.outputs.filename }}
        path: ${{ steps.build.outputs.filename }}
