name: CI

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=local,dest=${PWD}/builder" \
          --file Dockerfile .

    - name: Build package
      run: |
        install -vDm644 DEBIAN/raspberry-client.service pkg/etc/systemd/system/raspberry-client.service
        install -vdm755 pkg/opt
        cp -pr DEBIAN pkg
        mv builder/opt/raspberry-client pkg/opt
        dpkg-deb -b pkg raspberry-client-0.1.deb
        #tar czf raspberry-client.tar.gz raspberry-client
        ls

    - name: Archive package
      uses: actions/upload-artifact@v1
      with:
        name: raspberry-client-0.1.deb
        path: raspberry-client-0.1.deb
