name: CI

on:
  push:
    branches: [ workflow-deb ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v6 \
          --output "type=local,dest=${PWD}/builder" \
          --file Dockerfile .

    - name: Build package
      run: |
        sudo apt install -y debhelper
        install -vdm755 opt
        mv builder/opt/door-system opt
        dpkg-buildpackage -us -uc

    - name: Archive package
      uses: actions/upload-artifact@v1
      with:
        name: door-system_0.1_all.deb
        path: ../door-system_0.1_all.deb
