name: CI

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v6 \
          --output "type=local,dest=${PWD}/builder" \
          --file Dockerfile .

    - name: Build package
      run: |
        install -vDm644 DEBIAN/raspberry-client.service pkg/etc/systemd/system/raspberry-client.service
        install -vdm755 pkg/{opt,lib}
        cp -pr DEBIAN pkg
        mv builder/opt/raspberry-client pkg/opt
        ln -sf /lib/ld-linux.so.3 pkg/lib/libc.musl-armv7.so.1
        ln -sf /lib/ld-linux.so.3 pkg/lib/libc.musl-armhf.so.1
        ln -sf /usr/bin/python3 pkg/opt/raspberry-client/nfc_venv/bin/python
        sudo chown -R root:root pkg
        dpkg-deb -b pkg raspberry-client-0.1.deb
        ls

    - name: Archive package
      uses: actions/upload-artifact@v1
      with:
        name: raspberry-client-0.1.deb
        path: raspberry-client-0.1.deb
